package au.com.sensis.mobile.web.component.core.device;

import au.com.sensis.mobile.web.component.core.device.generated.AbstractDeviceConfig;
import au.com.sensis.wireless.common.volantis.devicerepository.api.Device;

/**
 * Simple interface for a registry that maps {@link Device}s to corresponding
 * configuration.
 *
 * @author Adrian.Koh2@sensis.com.au
 */
public interface DeviceConfigRegistry {

    /**
     * Get the configuration for the given device.
     *
     * @param device
     *            Device to get the configuration from.
     * @return configuration for the given device. . Note that this is an
     *         abstract class instead of an interface. The latter would be
     *         preferred but this class is generated by JAXB from an XSD.
     * @throws DeviceConfigRegistryException
     *             Thrown if any error occurs.
     */
    AbstractDeviceConfig getDeviceConfig(final Device device)
            throws DeviceConfigRegistryException;

}
